// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNtdXr47xjKQOydo96uvzjYviZmO31jPo',
    appId: '1:340185921376:web:5d088b0e41e027439bd005',
    messagingSenderId: '340185921376',
    projectId: 'rapidx-c05d4',
    authDomain: 'rapidx-c05d4.firebaseapp.com',
    storageBucket: 'rapidx-c05d4.firebasestorage.app',
    measurementId: 'G-25K8KBB70R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkQnHkJYyzQfnGECA5-iVDs0cfRcwuyoY',
    appId: '1:340185921376:android:eba1f78c3a4eb73e9bd005',
    messagingSenderId: '340185921376',
    projectId: 'rapidx-c05d4',
    storageBucket: 'rapidx-c05d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1zllyGgOukpjMZbW5FlHI2z8OX2XKP9A',
    appId: '1:340185921376:ios:f5d9a5d695c916a29bd005',
    messagingSenderId: '340185921376',
    projectId: 'rapidx-c05d4',
    storageBucket: 'rapidx-c05d4.firebasestorage.app',
    iosBundleId: 'com.app.vayalaNfcApp',
  );
}
